export interface CurriculumLesson {
  id: string
  title: string
  duration_mins: number
  order_index: number
  is_free_preview: boolean
  youtube_url?: string   // full YouTube URL, e.g. https://www.youtube.com/watch?v=VIDEO_ID
}

export interface CurriculumModule {
  id: string
  title: string
  order_index: number
  lessons: CurriculumLesson[]
}

function lesson(
  id: string, title: string, duration_mins: number,
  order_index: number, is_free_preview = false, youtube_url?: string
): CurriculumLesson {
  return { id, title, duration_mins, order_index, is_free_preview, youtube_url }
}

function mod(
  id: string, title: string, order_index: number,
  lessons: CurriculumLesson[]
): CurriculumModule {
  return { id, title, order_index, lessons }
}

export const COURSE_CURRICULUM: Record<string, CurriculumModule[]> = {

  /* ─────────────────────────────────────────────────── */
  'digital-marketing-mastery': [
    mod('dmm-m1', 'Foundations of Digital Marketing', 1, [
      lesson('dmm-m1-l1', 'What is Digital Marketing?', 15, 1, true, 'https://www.youtube.com/watch?v=bixR-KIJKYM'),
      lesson('dmm-m1-l2', 'The Nigerian Digital Landscape in 2025', 15, 2),
      lesson('dmm-m1-l3', 'Understanding Your Target Audience', 20, 3),
      lesson('dmm-m1-l4', 'Key Digital Marketing Channels', 20, 4),
      lesson('dmm-m1-l5', 'Setting Up Your Marketing Toolkit', 15, 5),
      lesson('dmm-m1-l6', 'Building a Digital Brand Identity', 20, 6),
    ]),
    mod('dmm-m2', 'Social Media Marketing', 2, [
      lesson('dmm-m2-l1', 'Instagram for Business', 20, 1, true),
      lesson('dmm-m2-l2', 'Facebook & Meta Ads for Nigerian Businesses', 25, 2),
      lesson('dmm-m2-l3', 'Twitter / X Marketing Strategy', 20, 3),
      lesson('dmm-m2-l4', 'TikTok & Short-Form Video Marketing', 20, 4),
      lesson('dmm-m2-l5', 'WhatsApp Business Marketing', 20, 5),
      lesson('dmm-m2-l6', 'Creating Viral Content', 25, 6),
    ]),
    mod('dmm-m3', 'SEO & Content Strategy', 3, [
      lesson('dmm-m3-l1', 'Introduction to SEO', 20, 1, true),
      lesson('dmm-m3-l2', 'Keyword Research for Nigerian Markets', 25, 2),
      lesson('dmm-m3-l3', 'On-Page SEO Techniques', 20, 3),
      lesson('dmm-m3-l4', 'Content Marketing Strategy', 25, 4),
      lesson('dmm-m3-l5', 'Blogging for Business Growth', 20, 5),
      lesson('dmm-m3-l6', 'Email Marketing Basics', 20, 6),
    ]),
    mod('dmm-m4', 'Ads, Analytics & Getting Clients', 4, [
      lesson('dmm-m4-l1', 'Google Ads for Beginners', 25, 1, true),
      lesson('dmm-m4-l2', 'Running Facebook Ad Campaigns', 25, 2),
      lesson('dmm-m4-l3', 'Reading Marketing Analytics', 20, 3),
      lesson('dmm-m4-l4', 'Campaign Optimisation & A/B Testing', 25, 4),
      lesson('dmm-m4-l5', 'Pricing Your Marketing Services', 20, 5),
      lesson('dmm-m4-l6', 'Building Your Portfolio & Getting Clients', 30, 6),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'social-media-management': [
    mod('smm-m1', 'Platform Mastery', 1, [
      lesson('smm-m1-l1', 'Understanding Social Media Algorithms', 15, 1, true, 'https://www.youtube.com/watch?v=XRr4c-mZuNk'),
      lesson('smm-m1-l2', 'Instagram Growth Strategy', 20, 2),
      lesson('smm-m1-l3', 'Facebook Page Management', 20, 3),
      lesson('smm-m1-l4', 'Twitter / X for Brands', 15, 4),
      lesson('smm-m1-l5', 'LinkedIn for B2B & Professionals', 20, 5),
      lesson('smm-m1-l6', 'TikTok Content Creation', 20, 6),
    ]),
    mod('smm-m2', 'Content Creation & Scheduling', 2, [
      lesson('smm-m2-l1', 'Developing a Content Calendar', 20, 1, true),
      lesson('smm-m2-l2', 'Writing Engaging Captions', 15, 2),
      lesson('smm-m2-l3', 'Designing Visual Content with Canva', 25, 3),
      lesson('smm-m2-l4', 'Shooting & Editing Short Videos', 25, 4),
      lesson('smm-m2-l5', 'Hashtag Research Strategy', 15, 5),
      lesson('smm-m2-l6', 'Content Scheduling Tools (Buffer, Later)', 20, 6),
    ]),
    mod('smm-m3', 'Client Management & Growth', 3, [
      lesson('smm-m3-l1', 'Finding Social Media Management Clients', 20, 1, true),
      lesson('smm-m3-l2', 'Client Onboarding & Reporting', 20, 2),
      lesson('smm-m3-l3', 'Community Management & Engagement', 20, 3),
      lesson('smm-m3-l4', 'Influencer & Creator Partnerships', 20, 4),
      lesson('smm-m3-l5', 'Running Paid Social Campaigns for Clients', 25, 5),
      lesson('smm-m3-l6', 'Scaling to a Social Media Agency', 30, 6),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'coding-basics': [
    mod('cb-m1', 'HTML Fundamentals', 1, [
      lesson('cb-m1-l1', 'What is Coding? Your First Webpage', 15, 1, true, 'https://www.youtube.com/watch?v=UB1O30fR-EE'),
      lesson('cb-m1-l2', 'Setting Up VS Code & Your Workspace', 20, 2),
      lesson('cb-m1-l3', 'HTML Tags, Structure & Headings', 25, 3),
      lesson('cb-m1-l4', 'Links, Images & Media', 20, 4),
      lesson('cb-m1-l5', 'HTML Forms & Inputs', 20, 5),
      lesson('cb-m1-l6', 'Tables, Lists & Semantic HTML', 20, 6),
      lesson('cb-m1-l7', 'Project: Build Your Personal HTML Page', 30, 7),
    ]),
    mod('cb-m2', 'CSS Styling', 2, [
      lesson('cb-m2-l1', 'Introduction to CSS', 15, 1, true),
      lesson('cb-m2-l2', 'Colours, Fonts & Text Styling', 20, 2),
      lesson('cb-m2-l3', 'The Box Model (Margin, Padding, Border)', 25, 3),
      lesson('cb-m2-l4', 'Flexbox Layout', 25, 4),
      lesson('cb-m2-l5', 'CSS Grid', 25, 5),
      lesson('cb-m2-l6', 'Responsive Design & Media Queries', 25, 6),
      lesson('cb-m2-l7', 'Project: Style Your Personal Page', 30, 7),
    ]),
    mod('cb-m3', 'JavaScript Basics', 3, [
      lesson('cb-m3-l1', 'Introduction to JavaScript', 20, 1, true),
      lesson('cb-m3-l2', 'Variables, Data Types & Operators', 20, 2),
      lesson('cb-m3-l3', 'Functions, Loops & Conditionals', 25, 3),
      lesson('cb-m3-l4', 'DOM Manipulation — Change Page Elements', 25, 4),
      lesson('cb-m3-l5', 'Events & User Interactions', 25, 5),
      lesson('cb-m3-l6', 'Fetch API — Load Data from the Internet', 25, 6),
      lesson('cb-m3-l7', 'Project: Build a Quiz App', 30, 7),
    ]),
    mod('cb-m4', 'Launch & Earn', 4, [
      lesson('cb-m4-l1', 'Git Version Control & GitHub', 20, 1, true),
      lesson('cb-m4-l2', 'Deploying to GitHub Pages — Free Hosting', 20, 2),
      lesson('cb-m4-l3', 'Making Money as a Freelance Developer', 25, 3),
      lesson('cb-m4-l4', 'Building Your Developer Portfolio', 25, 4),
      lesson('cb-m4-l5', 'Finding Clients on Upwork & Fiverr', 20, 5),
      lesson('cb-m4-l6', 'Final Project: Full Personal Website', 30, 6),
      lesson('cb-m4-l7', 'Course Review & Certification', 20, 7),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'python-data-skills': [
    mod('pds-m1', 'Python Foundations', 1, [
      lesson('pds-m1-l1', 'Why Python? Installing & Running Code', 20, 1, true, 'https://www.youtube.com/watch?v=rfscVS0vtbw'),
      lesson('pds-m1-l2', 'Variables, Strings & Numbers', 20, 2),
      lesson('pds-m1-l3', 'Lists, Tuples & Dictionaries', 25, 3),
      lesson('pds-m1-l4', 'If/Else Statements & Logic', 20, 4),
      lesson('pds-m1-l5', 'Loops: For & While', 25, 5),
      lesson('pds-m1-l6', 'Functions & Modules', 25, 6),
      lesson('pds-m1-l7', 'Reading & Writing Files', 20, 7),
      lesson('pds-m1-l8', 'Error Handling with Try/Except', 20, 8),
      lesson('pds-m1-l9', 'Project: Build a Simple Calculator', 30, 9),
      lesson('pds-m1-l10', 'Python Basics Review & Quiz', 20, 10),
    ]),
    mod('pds-m2', 'Data Analysis with Pandas', 2, [
      lesson('pds-m2-l1', 'Introduction to Data Science', 20, 1, true),
      lesson('pds-m2-l2', 'NumPy: Numerical Computing Basics', 25, 2),
      lesson('pds-m2-l3', 'Pandas: Loading & Exploring Datasets', 25, 3),
      lesson('pds-m2-l4', 'Cleaning & Transforming Data', 25, 4),
      lesson('pds-m2-l5', 'Filtering, Grouping & Aggregating', 25, 5),
      lesson('pds-m2-l6', 'Merging & Joining DataFrames', 25, 6),
      lesson('pds-m2-l7', 'Analysing Nigerian Economic Data', 30, 7),
      lesson('pds-m2-l8', 'Project: Analyse a Real Nigerian Dataset', 35, 8),
      lesson('pds-m2-l9', 'Pandas Review & Best Practices', 20, 9),
      lesson('pds-m2-l10', 'Mid-Course Assessment', 25, 10),
    ]),
    mod('pds-m3', 'Data Visualisation', 3, [
      lesson('pds-m3-l1', 'Introduction to Matplotlib', 20, 1, true),
      lesson('pds-m3-l2', 'Bar Charts, Line Charts & Histograms', 25, 2),
      lesson('pds-m3-l3', 'Seaborn: Beautiful Statistical Charts', 25, 3),
      lesson('pds-m3-l4', 'Interactive Charts with Plotly', 25, 4),
      lesson('pds-m3-l5', 'Storytelling with Data', 25, 5),
      lesson('pds-m3-l6', 'Building a Data Dashboard', 30, 6),
      lesson('pds-m3-l7', 'Visualising Nigerian Business Data', 30, 7),
      lesson('pds-m3-l8', 'Project: Present Insights as a Report', 35, 8),
      lesson('pds-m3-l9', 'Visualisation Review & Quiz', 20, 9),
    ]),
    mod('pds-m4', 'Career in Data & Freelancing', 4, [
      lesson('pds-m4-l1', 'Machine Learning: A Gentle Introduction', 20, 1, true),
      lesson('pds-m4-l2', 'Building Your First ML Model', 30, 2),
      lesson('pds-m4-l3', 'Data Analyst vs Data Scientist — Which Path?', 20, 3),
      lesson('pds-m4-l4', 'Building a Data Portfolio on GitHub', 25, 4),
      lesson('pds-m4-l5', 'Freelancing as a Data Analyst in Nigeria', 25, 5),
      lesson('pds-m4-l6', 'SQL Basics for Data Analysts', 25, 6),
      lesson('pds-m4-l7', 'Final Project: End-to-End Data Analysis', 45, 7),
      lesson('pds-m4-l8', 'Course Wrap-Up & Certification', 20, 8),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'fashion-design-fundamentals': [
    mod('fdf-m1', 'Design Basics & Materials', 1, [
      lesson('fdf-m1-l1', 'Introduction to Fashion Design in Nigeria', 15, 1, true, 'https://www.youtube.com/watch?v=q-P-4sjHZ4c'),
      lesson('fdf-m1-l2', 'Fabrics: Ankara, Lace, Aso-oke & More', 20, 2),
      lesson('fdf-m1-l3', 'Taking Body Measurements Accurately', 20, 3),
      lesson('fdf-m1-l4', 'Essential Sewing Tools & Their Uses', 20, 4),
      lesson('fdf-m1-l5', 'Sketching & Fashion Illustration Basics', 25, 5),
      lesson('fdf-m1-l6', 'Colour Theory & Pattern Selection', 20, 6),
      lesson('fdf-m1-l7', 'Setting Up Your Workspace & Equipment', 15, 7),
    ]),
    mod('fdf-m2', 'Pattern Making & Cutting', 2, [
      lesson('fdf-m2-l1', 'Understanding Dress Patterns', 20, 1, true),
      lesson('fdf-m2-l2', 'Drafting a Basic Bodice Block', 30, 2),
      lesson('fdf-m2-l3', 'Drafting Skirt & Trouser Patterns', 30, 3),
      lesson('fdf-m2-l4', 'Grading Patterns for Different Sizes', 25, 4),
      lesson('fdf-m2-l5', 'Fabric Cutting Techniques', 25, 5),
      lesson('fdf-m2-l6', 'Adapting Patterns for Nigerian Styles', 25, 6),
      lesson('fdf-m2-l7', 'Project: Draft Your First Pattern', 30, 7),
    ]),
    mod('fdf-m3', 'Sewing & Construction', 3, [
      lesson('fdf-m3-l1', 'Sewing Machine Basics & Maintenance', 20, 1, true),
      lesson('fdf-m3-l2', 'Stitching Techniques — Seams & Hems', 25, 2),
      lesson('fdf-m3-l3', 'Sewing a Native Outfit (Buba & Skirt)', 35, 3),
      lesson('fdf-m3-l4', 'Sewing Western Styles & Corporate Wear', 35, 4),
      lesson('fdf-m3-l5', 'Zips, Buttons & Fasteners', 20, 5),
      lesson('fdf-m3-l6', 'Finishing Techniques & Quality Control', 25, 6),
      lesson('fdf-m3-l7', 'Project: Complete a Full Garment', 45, 7),
      lesson('fdf-m3-l8', 'Beading, Embroidery & Embellishments', 25, 8),
    ]),
    mod('fdf-m4', 'Business & Brand Building', 4, [
      lesson('fdf-m4-l1', 'Pricing Your Work for Profit', 20, 1, true),
      lesson('fdf-m4-l2', 'Registering Your Fashion Business in Nigeria', 20, 2),
      lesson('fdf-m4-l3', 'Photography for Fashion — Using Your Phone', 20, 3),
      lesson('fdf-m4-l4', 'Selling on Instagram & WhatsApp', 20, 4),
      lesson('fdf-m4-l5', 'Getting Orders from Corporate Clients', 20, 5),
      lesson('fdf-m4-l6', 'Managing Clients & Delivery Deadlines', 20, 6),
      lesson('fdf-m4-l7', 'Scaling — Hiring Apprentices', 20, 7),
      lesson('fdf-m4-l8', 'Final Project: Full Collection Lookbook', 30, 8),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'solar-installation-tech': [
    mod('sit-m1', 'Solar Energy Fundamentals', 1, [
      lesson('sit-m1-l1', 'How Solar Energy Works', 20, 1, true, 'https://www.youtube.com/watch?v=xKxrkht7CpY'),
      lesson('sit-m1-l2', 'Types of Solar Systems (On-Grid, Off-Grid, Hybrid)', 20, 2),
      lesson('sit-m1-l3', 'Nigeria\'s Energy Crisis & Solar Opportunity', 15, 3),
      lesson('sit-m1-l4', 'Solar Panel Types & Efficiency Ratings', 25, 4),
      lesson('sit-m1-l5', 'Reading & Interpreting Solar Specs', 20, 5),
      lesson('sit-m1-l6', 'Safety Rules for Electrical Work', 20, 6),
      lesson('sit-m1-l7', 'Tools Every Solar Installer Needs', 15, 7),
    ]),
    mod('sit-m2', 'System Components & Design', 2, [
      lesson('sit-m2-l1', 'Solar Panels — Selection & Sizing', 25, 1, true),
      lesson('sit-m2-l2', 'Batteries — Deep Cycle & Lithium-Ion', 25, 2),
      lesson('sit-m2-l3', 'Charge Controllers — PWM vs MPPT', 25, 3),
      lesson('sit-m2-l4', 'Inverters — Pure Sine vs Modified Sine', 25, 4),
      lesson('sit-m2-l5', 'Load Assessment — Calculating Energy Needs', 30, 5),
      lesson('sit-m2-l6', 'System Sizing for a Nigerian Home', 30, 6),
      lesson('sit-m2-l7', 'Drawing Wiring Diagrams', 25, 7),
    ]),
    mod('sit-m3', 'Installation & Wiring', 3, [
      lesson('sit-m3-l1', 'Mounting Solar Panels on Rooftops', 30, 1, true),
      lesson('sit-m3-l2', 'Wiring Panels in Series & Parallel', 30, 2),
      lesson('sit-m3-l3', 'Connecting the Battery Bank', 25, 3),
      lesson('sit-m3-l4', 'Installing the Charge Controller', 25, 4),
      lesson('sit-m3-l5', 'Inverter Connection & AC Wiring', 25, 5),
      lesson('sit-m3-l6', 'Testing & Commissioning a System', 30, 6),
      lesson('sit-m3-l7', 'Project: Full System Installation Simulation', 45, 7),
    ]),
    mod('sit-m4', 'Maintenance & Business', 4, [
      lesson('sit-m4-l1', 'Troubleshooting Common Solar Problems', 25, 1, true),
      lesson('sit-m4-l2', 'Preventive Maintenance Schedule', 20, 2),
      lesson('sit-m4-l3', 'Fault Finding with a Multimeter', 25, 3),
      lesson('sit-m4-l4', 'Pricing Solar Installations in Nigeria', 25, 4),
      lesson('sit-m4-l5', 'Getting Certified by NAFDAC/NEMSA', 20, 5),
      lesson('sit-m4-l6', 'Building a Solar Installation Business', 25, 6),
      lesson('sit-m4-l7', 'Final Assessment & Certification', 30, 7),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'agribusiness-fundamentals': [
    mod('ab-m1', 'Modern Farming Basics', 1, [
      lesson('ab-m1-l1', 'Agriculture as a Business, Not a Subsistence', 15, 1, true, 'https://www.youtube.com/watch?v=pJm5c8-sJXA'),
      lesson('ab-m1-l2', 'Understanding Nigerian Farming Seasons & Climate Zones', 20, 2),
      lesson('ab-m1-l3', 'Soil Health & Fertility Management', 20, 3),
      lesson('ab-m1-l4', 'Water Management & Irrigation for SME Farmers', 20, 4),
      lesson('ab-m1-l5', 'Sourcing Quality Seeds & Inputs', 15, 5),
    ]),
    mod('ab-m2', 'Crop & Livestock Production', 2, [
      lesson('ab-m2-l1', 'High-Value Crops: Maize, Tomatoes, Cassava', 20, 1, true),
      lesson('ab-m2-l2', 'Poultry Farming for Profit', 25, 2),
      lesson('ab-m2-l3', 'Fish Farming (Catfish & Tilapia)', 25, 3),
      lesson('ab-m2-l4', 'Snail & Mushroom Farming — Low Capital Options', 20, 4),
      lesson('ab-m2-l5', 'Pest & Disease Control', 20, 5),
    ]),
    mod('ab-m3', 'Agribusiness Finance', 3, [
      lesson('ab-m3-l1', 'Costing & Budgeting for Farming', 20, 1, true),
      lesson('ab-m3-l2', 'Accessing CBN & State Agricultural Grants', 20, 2),
      lesson('ab-m3-l3', 'Cooperative Farming & Group Finance', 15, 3),
      lesson('ab-m3-l4', 'Keeping Farm Records & Financial Statements', 20, 4),
      lesson('ab-m3-l5', 'Break-Even Analysis for Your Farm', 20, 5),
    ]),
    mod('ab-m4', 'Marketing & Supply Chain', 4, [
      lesson('ab-m4-l1', 'Finding Buyers: Markets, Hotels & Supermarkets', 20, 1, true),
      lesson('ab-m4-l2', 'Value Addition — Processing & Packaging', 25, 2),
      lesson('ab-m4-l3', 'Selling Agro Products Online', 20, 3),
      lesson('ab-m4-l4', 'Reducing Post-Harvest Losses', 20, 4),
      lesson('ab-m4-l5', 'Building Your Agribusiness Brand', 20, 5),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'financial-literacy-nigeria': [
    mod('fl-m1', 'Money Mindset & Foundations', 1, [
      lesson('fl-m1-l1', 'Why Most Nigerians Struggle with Money', 15, 1, true, 'https://www.youtube.com/watch?v=HQzoZfc3GwQ'),
      lesson('fl-m1-l2', 'Income Types: Salary, Business, Passive Income', 20, 2),
      lesson('fl-m1-l3', 'Understanding Needs vs. Wants', 15, 3),
      lesson('fl-m1-l4', 'Setting SMART Financial Goals', 20, 4),
      lesson('fl-m1-l5', 'The Power of Compound Interest', 15, 5),
    ]),
    mod('fl-m2', 'Budgeting, Saving & Debt', 2, [
      lesson('fl-m2-l1', 'Creating a Monthly Budget on Any Income', 20, 1, true),
      lesson('fl-m2-l2', 'The 50/30/20 Budget Rule Adapted for Nigeria', 15, 2),
      lesson('fl-m2-l3', 'Building an Emergency Fund', 20, 3),
      lesson('fl-m2-l4', 'Good Debt vs. Bad Debt', 20, 4),
      lesson('fl-m2-l5', 'Escaping the Loan Trap — Esusu & Ajo Alternatives', 20, 5),
    ]),
    mod('fl-m3', 'Investing & Growing Wealth', 3, [
      lesson('fl-m3-l1', 'Introduction to Investing in Nigeria', 20, 1, true),
      lesson('fl-m3-l2', 'Nigerian Stock Exchange & How to Buy Stocks', 25, 2),
      lesson('fl-m3-l3', 'Treasury Bills, Bonds & Fixed Income', 20, 3),
      lesson('fl-m3-l4', 'Real Estate Investment for Nigerians', 20, 4),
      lesson('fl-m3-l5', 'Building Multiple Streams of Income', 25, 5),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'entrepreneurship-nigeria': [
    mod('en-m1', 'The Entrepreneur Mindset', 1, [
      lesson('en-m1-l1', 'What Makes a Successful Nigerian Entrepreneur?', 15, 1, true, 'https://www.youtube.com/watch?v=ZoqgAy3h4DM'),
      lesson('en-m1-l2', 'Identifying Problems Worth Solving', 20, 2),
      lesson('en-m1-l3', 'From Idea to Opportunity — The Validation Test', 20, 3),
      lesson('en-m1-l4', 'Building Resilience & Managing Failure', 15, 4),
      lesson('en-m1-l5', 'Nigerian Success Stories to Learn From', 15, 5),
    ]),
    mod('en-m2', 'Business Planning & Validation', 2, [
      lesson('en-m2-l1', 'Writing a One-Page Business Plan', 20, 1, true),
      lesson('en-m2-l2', 'Market Research in Nigerian Contexts', 25, 2),
      lesson('en-m2-l3', 'Defining Your Unique Value Proposition', 20, 3),
      lesson('en-m2-l4', 'Your First 100 Customers Strategy', 20, 4),
      lesson('en-m2-l5', 'Minimum Viable Product (MVP) — Build Small, Learn Fast', 20, 5),
      lesson('en-m2-l6', 'Competitive Analysis — Know Your Market', 20, 6),
    ]),
    mod('en-m3', 'Finance & Funding', 3, [
      lesson('en-m3-l1', 'Bootstrapping vs. Raising Capital', 20, 1, true),
      lesson('en-m3-l2', 'Nigerian Grants & Loans: SMEDAN, BOI, TEF', 25, 2),
      lesson('en-m3-l3', 'Business Banking & Opening a Corporate Account', 15, 3),
      lesson('en-m3-l4', 'Pricing for Profit — Not Just Revenue', 20, 4),
      lesson('en-m3-l5', 'Reading a Profit & Loss Statement', 20, 5),
    ]),
    mod('en-m4', 'Growth & Scale', 4, [
      lesson('en-m4-l1', 'Registering with CAC — Step by Step', 20, 1, true),
      lesson('en-m4-l2', 'Building a Sales System', 25, 2),
      lesson('en-m4-l3', 'Hiring Your First Team Member', 20, 3),
      lesson('en-m4-l4', 'Digital Tools to Run a Lean Business', 20, 4),
      lesson('en-m4-l5', 'Exporting Nigerian Products — Global Opportunities', 20, 5),
      lesson('en-m4-l6', 'Pitching to Investors & Competitions', 25, 6),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'graphic-design-canva': [
    mod('gdc-m1', 'Design Fundamentals', 1, [
      lesson('gdc-m1-l1', 'What Makes a Great Design?', 15, 1, true, 'https://www.youtube.com/watch?v=qB2H5Q62s-Y'),
      lesson('gdc-m1-l2', 'Colour Theory & Psychology', 20, 2),
      lesson('gdc-m1-l3', 'Typography — Choosing & Pairing Fonts', 20, 3),
      lesson('gdc-m1-l4', 'Layout, Balance & White Space', 20, 4),
      lesson('gdc-m1-l5', 'Branding Basics — Logo, Colours & Voice', 25, 5),
      lesson('gdc-m1-l6', 'Project: Create a Mood Board', 20, 6),
    ]),
    mod('gdc-m2', 'Canva Mastery', 2, [
      lesson('gdc-m2-l1', 'Canva Interface & Essential Features', 15, 1, true),
      lesson('gdc-m2-l2', 'Social Media Graphics & Story Templates', 25, 2),
      lesson('gdc-m2-l3', 'Designing Flyers & Posters for Nigerian Events', 25, 3),
      lesson('gdc-m2-l4', 'Business Cards, Letterheads & Stationery', 20, 4),
      lesson('gdc-m2-l5', 'Canva Presentations & Pitch Decks', 20, 5),
      lesson('gdc-m2-l6', 'Canva Video & Animated Posts', 20, 6),
      lesson('gdc-m2-l7', 'Project: Complete Brand Kit in Canva', 30, 7),
    ]),
    mod('gdc-m3', 'Photoshop & Advanced Editing', 3, [
      lesson('gdc-m3-l1', 'Photoshop Interface & Layers', 20, 1, true),
      lesson('gdc-m3-l2', 'Selection Tools & Removing Backgrounds', 25, 2),
      lesson('gdc-m3-l3', 'Photo Retouching & Colour Correction', 25, 3),
      lesson('gdc-m3-l4', 'Creating Mockups for Products', 25, 4),
      lesson('gdc-m3-l5', 'Typography Effects in Photoshop', 25, 5),
      lesson('gdc-m3-l6', 'Exporting for Print vs Digital', 15, 6),
      lesson('gdc-m3-l7', 'Project: Product Packaging Design', 30, 7),
    ]),
    mod('gdc-m4', 'Freelance Design Career', 4, [
      lesson('gdc-m4-l1', 'Building a Design Portfolio', 20, 1, true),
      lesson('gdc-m4-l2', 'Pricing Your Design Services', 20, 2),
      lesson('gdc-m4-l3', 'Finding Clients on Fiverr, Instagram & LinkedIn', 20, 3),
      lesson('gdc-m4-l4', 'Managing Client Feedback & Revisions', 15, 4),
      lesson('gdc-m4-l5', 'Contracts & Getting Paid on Time', 15, 5),
      lesson('gdc-m4-l6', 'Scaling to a Design Studio', 20, 6),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'catering-food-business': [
    mod('cfb-m1', 'Food Business Foundations', 1, [
      lesson('cfb-m1-l1', 'Is a Food Business Right for You?', 15, 1, true, 'https://www.youtube.com/watch?v=EUXnJraKM3k'),
      lesson('cfb-m1-l2', 'Nigerian Food Market Opportunities', 20, 2),
      lesson('cfb-m1-l3', 'Food Safety, Hygiene & NAFDAC Basics', 20, 3),
      lesson('cfb-m1-l4', 'Choosing Your Food Business Model', 20, 4),
    ]),
    mod('cfb-m2', 'Recipes, Menus & Costing', 2, [
      lesson('cfb-m2-l1', 'Building a Profitable Menu', 20, 1, true),
      lesson('cfb-m2-l2', 'Food Costing — Price Right for Profit', 25, 2),
      lesson('cfb-m2-l3', 'Scaling Recipes from Home to Bulk', 20, 3),
      lesson('cfb-m2-l4', 'Specialty Diets & Modern Nigerian Cuisine', 20, 4),
    ]),
    mod('cfb-m3', 'Kitchen Operations & Delivery', 3, [
      lesson('cfb-m3-l1', 'Setting Up a Commercial Kitchen on a Budget', 20, 1, true),
      lesson('cfb-m3-l2', 'Equipment Sourcing & Maintenance', 20, 2),
      lesson('cfb-m3-l3', 'Packaging, Branding & Presentation', 20, 3),
      lesson('cfb-m3-l4', 'Working with Food Delivery Platforms', 20, 4),
    ]),
    mod('cfb-m4', 'Marketing & Business Growth', 4, [
      lesson('cfb-m4-l1', 'Instagram & WhatsApp Marketing for Food', 20, 1, true),
      lesson('cfb-m4-l2', 'Catering for Events — Pricing & Logistics', 25, 2),
      lesson('cfb-m4-l3', 'Getting Corporate & Office Catering Contracts', 20, 3),
      lesson('cfb-m4-l4', 'Scaling: From Home Kitchen to a Catering Company', 25, 4),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'logistics-supply-chain': [
    mod('lsc-m1', 'Supply Chain Fundamentals', 1, [
      lesson('lsc-m1-l1', 'What is Supply Chain & Why It Matters in Nigeria', 15, 1, true, 'https://www.youtube.com/watch?v=Mi6OJ4zbLX4'),
      lesson('lsc-m1-l2', 'The Supply Chain — From Farm to Consumer', 20, 2),
      lesson('lsc-m1-l3', 'Key Players in Nigerian Logistics', 20, 3),
      lesson('lsc-m1-l4', 'Supply Chain Disruptions & Solutions', 20, 4),
      lesson('lsc-m1-l5', 'Introduction to Procurement', 20, 5),
    ]),
    mod('lsc-m2', 'Inventory & Warehousing', 2, [
      lesson('lsc-m2-l1', 'Inventory Management Basics', 20, 1, true),
      lesson('lsc-m2-l2', 'Just-In-Time vs Bulk Stocking', 20, 2),
      lesson('lsc-m2-l3', 'Warehouse Layout & Organisation', 20, 3),
      lesson('lsc-m2-l4', 'Using Technology for Inventory Tracking', 20, 4),
    ]),
    mod('lsc-m3', 'Transport & Last-Mile Delivery', 3, [
      lesson('lsc-m3-l1', 'Road vs Air vs Sea Freight in Nigeria', 20, 1, true),
      lesson('lsc-m3-l2', 'Last-Mile Delivery Challenges & Solutions', 20, 2),
      lesson('lsc-m3-l3', 'Working with Dispatch Riders & Fleet', 20, 3),
      lesson('lsc-m3-l4', 'Import & Export Documentation Basics', 25, 4),
    ]),
    mod('lsc-m4', 'Career & Freelancing in Logistics', 4, [
      lesson('lsc-m4-l1', 'Supply Chain Career Paths in Nigeria', 15, 1, true),
      lesson('lsc-m4-l2', 'Starting a Logistics / Dispatch Business', 25, 2),
      lesson('lsc-m4-l3', 'Using Apps: Kwik, Gokada, Bolt Food — B2B Opportunities', 20, 3),
      lesson('lsc-m4-l4', 'Certifications: CILT, APICS & More', 20, 4),
      lesson('lsc-m4-l5', 'Final Project & Course Assessment', 30, 5),
    ]),
  ],

  /* ═══════════════════════════════════════════════════════════════════════════
     NIGERIAN LANGUAGES  —  NERDC-Aligned Curricula
     Scope: JSS1–SS3 National Curriculum + WAEC/NECO oral & written syllabuses
     All three courses follow the same six-module framework:
       1. Phonology & Orthography
       2. Everyday Communication & Vocabulary
       3. Grammar (NERDC SS1–SS3 scope)
       4. Reading & Writing Skills
       5. Literature & Oral Tradition
       6. Culture, Heritage & Pedagogy
  ═══════════════════════════════════════════════════════════════════════════ */

  /* ─────────────────────────────────────────────────── YORUBA ─────────────── */
  'yoruba-language-teaching': [

    mod('yor-m1', 'Phonology, Tones & the Yoruba Alphabet', 1, [
      lesson('yor-m1-l1',
        'Introduction to Yoruba — History, Dialects & the Standard Variety',
        15, 1, true, 'https://www.youtube.com/watch?v=siyXkR-2ZcU'),
      lesson('yor-m1-l2',
        'The Yoruba Alphabet — 25 Letters, Digraphs & Standard Orthography (NERDC/IYC)',
        20, 2),
      lesson('yor-m1-l3',
        'The Three Lexical Tones — High (´), Mid (–), Low (`) & Tone Marks',
        25, 3),
      lesson('yor-m1-l4',
        'Vowels (Oral & Nasal), Diphthongs & the Syllabic Nasal (n̄)',
        20, 4),
      lesson('yor-m1-l5',
        'Special Consonants — gb, kp, ṣ, and Labiovelar Sounds',
        20, 5),
      lesson('yor-m1-l6',
        'Tone Sandhi — Elision, Assimilation & Connected Speech Rules',
        25, 6),
    ]),

    mod('yor-m2', 'Everyday Communication & Vocabulary Building', 2, [
      lesson('yor-m2-l1',
        'Greetings — Morning, Afternoon, Evening, Festivals & Formal Occasions',
        20, 1, true),
      lesson('yor-m2-l2',
        'Family, Relationships & Forms of Address (Baba, Ìyá, Bràdà, etc.)',
        20, 2),
      lesson('yor-m2-l3',
        'Numbers, Counting & Vigesimal (Base-20) Arithmetic in Yoruba',
        25, 3),
      lesson('yor-m2-l4',
        'Market Language — Bargaining, Prices, Quantities & Transactions',
        20, 4),
      lesson('yor-m2-l5',
        'Days (Àjé to Àbámẹ́ta), Months, Seasons & Telling the Time',
        20, 5),
      lesson('yor-m2-l6',
        'Colours, Shapes, Directions & Common Descriptive Vocabulary',
        20, 6),
    ]),

    mod('yor-m3', 'Yoruba Grammar — NERDC SS1–SS3 Scope', 3, [
      lesson('yor-m3-l1',
        'Nouns — Classes, Nominal Phrases & Noun Modification',
        20, 1, true),
      lesson('yor-m3-l2',
        'Pronouns — Personal, Possessive, Reflexive & Demonstrative',
        20, 2),
      lesson('yor-m3-l3',
        'Verbs — Base Form, Tense Markers (ti, máa, yóò) & Aspect',
        25, 3),
      lesson('yor-m3-l4',
        'Adjectives, Adverbs & Intensifiers in Yoruba',
        20, 4),
      lesson('yor-m3-l5',
        'Sentence Structure (SVO), Compound & Complex Sentences',
        25, 5),
      lesson('yor-m3-l6',
        'Questions (Direct & Indirect), Negation (kò, ò) & Commands',
        20, 6),
      lesson('yor-m3-l7',
        'Prepositions, Conjunctions & Discourse Markers',
        20, 7),
    ]),

    mod('yor-m4', 'Reading & Writing Skills', 4, [
      lesson('yor-m4-l1',
        'Reading Yoruba Texts — Decoding Tones, Diacritics & Fluency',
        20, 1, true),
      lesson('yor-m4-l2',
        'Comprehension Strategies — Skimming, Scanning & Inference',
        20, 2),
      lesson('yor-m4-l3',
        'Composition Writing — Narrative, Descriptive & Argumentative Essays',
        25, 3),
      lesson('yor-m4-l4',
        'Formal Letter & Report Writing in Yoruba',
        25, 4),
      lesson('yor-m4-l5',
        'Summary Writing & Note-Taking Techniques',
        20, 5),
      lesson('yor-m4-l6',
        'Dictation, Spelling Accuracy & Tone-Mark Placement',
        20, 6),
    ]),

    mod('yor-m5', 'Literature & Oral Tradition (NERDC Set Works)', 5, [
      lesson('yor-m5-l1',
        'Owe — Proverbs: Structure, Classification & Contextual Use',
        20, 1, true),
      lesson('yor-m5-l2',
        'Oríkì — Praise Poetry, Lineage Chants & Personal Identity',
        25, 2),
      lesson('yor-m5-l3',
        'Àló Àpamọ̀ — Riddles, & Àló Àpagbè — Folktales & Fables',
        25, 3),
      lesson('yor-m5-l4',
        'Ewì — Modern Yoruba Poetry: Devices, Themes & Analysis',
        25, 4),
      lesson('yor-m5-l5',
        'Ìjálá, Rárà, Sàngó Pípè & Other Specialist Oral Genres',
        25, 5),
      lesson('yor-m5-l6',
        'Prose Set Text Study — Reading & Analysing a Yoruba Novel',
        30, 6),
      lesson('yor-m5-l7',
        'Drama Set Text Study — Staging & Analysing a Yoruba Play',
        30, 7),
    ]),

    mod('yor-m6', 'Culture, Heritage & Pedagogy', 6, [
      lesson('yor-m6-l1',
        'Yoruba Traditional Institutions — Obàship, Ìlú & Governance',
        20, 1, true),
      lesson('yor-m6-l2',
        'Yoruba Festivals — Ọ̀ṣun-Ọ̀ṣogbo, Egungun, Ṣàngó, Ògún',
        20, 2),
      lesson('yor-m6-l3',
        'Yoruba in the Diaspora — Brazil, Cuba, Trinidad & the Americas',
        20, 3),
      lesson('yor-m6-l4',
        'Lesson Planning for Yoruba Language Classes (JSS–SS)',
        25, 4),
      lesson('yor-m6-l5',
        'Teaching Tones & Orthography to Beginners — Strategies & Resources',
        25, 5),
      lesson('yor-m6-l6',
        'WAEC/NECO Oral & Written Exam Preparation — Paper Types & Tips',
        30, 6),
    ]),
  ],

  /* ─────────────────────────────────────────────────── IGBO ───────────────── */
  'igbo-language-teaching': [

    mod('ibo-m1', 'Phonology, Tones & the Onwu Alphabet', 1, [
      lesson('ibo-m1-l1',
        'Introduction to Igbo — History, Dialects & the Central (Standard) Igbo',
        15, 1, true, 'https://www.youtube.com/watch?v=5VgGXYhvAnc'),
      lesson('ibo-m1-l2',
        'The Onwu Alphabet (1961) — 36 Letters, Digraphs & NERDC Orthography',
        20, 2),
      lesson('ibo-m1-l3',
        'Igbo Tone System — High Tone, Low Tone & Downstep (Downglide)',
        25, 3),
      lesson('ibo-m1-l4',
        'Vowel Harmony — 8 Vowels, Two Sets & Harmony Rules',
        25, 4),
      lesson('ibo-m1-l5',
        'Consonants — Implosives (ị, ụ), Nasals & Labiovelar Sounds',
        20, 5),
      lesson('ibo-m1-l6',
        'Syllable Structure, Tone Marking & Connected Speech in Igbo',
        25, 6),
    ]),

    mod('ibo-m2', 'Everyday Communication & Vocabulary Building', 2, [
      lesson('ibo-m2-l1',
        'Greetings — Time-of-Day, Seasonal & Respect Greetings in Igbo',
        20, 1, true),
      lesson('ibo-m2-l2',
        'Family, Kinship Terms & Forms of Address (Nna, Nne, Ụmụ, etc.)',
        20, 2),
      lesson('ibo-m2-l3',
        'Numbers, Counting & Traditional Igbo Numeral System',
        25, 3),
      lesson('ibo-m2-l4',
        'Market Igbo — Ọchà Trading Language, Prices & Bargaining',
        20, 4),
      lesson('ibo-m2-l5',
        'Days (Eke, Orie, Afor, Nkwo), Months & Igbo Calendar',
        20, 5),
      lesson('ibo-m2-l6',
        'Food, Clothing, Household Items & Descriptive Vocabulary',
        20, 6),
    ]),

    mod('ibo-m3', 'Igbo Grammar — NERDC SS1–SS3 Scope', 3, [
      lesson('ibo-m3-l1',
        'Nouns — Classes (Animate/Inanimate), Gender & Noun Phrases',
        20, 1, true),
      lesson('ibo-m3-l2',
        'Pronouns — Personal, Possessive, Reflexive & Demonstrative',
        20, 2),
      lesson('ibo-m3-l3',
        'Verbs — Root, Extensions (Suffixes), Tense & Aspect Markers',
        25, 3),
      lesson('ibo-m3-l4',
        'Adjectives, Adjectival Clauses & Comparison in Igbo',
        20, 4),
      lesson('ibo-m3-l5',
        'Sentence Structure (SVO & Verb-Second), Coordination & Subordination',
        25, 5),
      lesson('ibo-m3-l6',
        'Questions (Ọ bụ, Ọlị), Negation (ọ bụghị, o nweghị) & Commands',
        20, 6),
      lesson('ibo-m3-l7',
        "Prepositions (n', na, n'ime), Conjunctions & Discourse Connectors",
        20, 7),
    ]),

    mod('ibo-m4', 'Reading & Writing Skills', 4, [
      lesson('ibo-m4-l1',
        'Reading Igbo Texts — Decoding Vowel Harmony & Tone Diacritics',
        20, 1, true),
      lesson('ibo-m4-l2',
        'Comprehension Strategies — Passage Analysis & Inference',
        20, 2),
      lesson('ibo-m4-l3',
        'Composition Writing — Narrative, Expository & Argumentative in Igbo',
        25, 3),
      lesson('ibo-m4-l4',
        'Letter Writing — Formal & Informal Correspondence in Igbo',
        25, 4),
      lesson('ibo-m4-l5',
        'Summary Writing, Précis & Note-Taking in Igbo',
        20, 5),
      lesson('ibo-m4-l6',
        'Dictation, Vowel Harmony Spelling & Diacritic Accuracy',
        20, 6),
    ]),

    mod('ibo-m5', 'Literature & Oral Tradition (NERDC Set Works)', 5, [
      lesson('ibo-m5-l1',
        'Ilu — Igbo Proverbs: Structure, Tonal Meaning & Social Function',
        20, 1, true),
      lesson('ibo-m5-l2',
        'Ifo — Folktales, Animal Fables & Moral Philosophy',
        25, 2),
      lesson('ibo-m5-l3',
        'Abụ — Igbo Songs & Oral Poetry: War Songs, Harvest Songs & Lullabies',
        25, 3),
      lesson('ibo-m5-l4',
        'Egwu & Mmọ — Masquerade Performances, Ritual Drama & Oral Theatre',
        25, 4),
      lesson('ibo-m5-l5',
        'Modern Igbo Poetry — Themes, Literary Devices & Close Reading',
        25, 5),
      lesson('ibo-m5-l6',
        'Prose Set Text — Reading & Analysing an Igbo Novel (NERDC Approved)',
        30, 6),
      lesson('ibo-m5-l7',
        'Drama Set Text — Analysing Structure, Character & Dialogue in Igbo Play',
        30, 7),
    ]),

    mod('ibo-m6', 'Culture, Heritage & Pedagogy', 6, [
      lesson('ibo-m6-l1',
        'Igbo Cosmology — Chukwu, Chi, Ala & the Spirit World',
        20, 1, true),
      lesson('ibo-m6-l2',
        'Igbo Festivals — Iri Ji (New Yam), Mmanwu (Masquerade) & Ọzọ Title',
        20, 2),
      lesson('ibo-m6-l3',
        'Igbo Democratic Traditions — Ọhanaeze, Umunna & Age-Grade Systems',
        20, 3),
      lesson('ibo-m6-l4',
        'Lesson Planning for Igbo Language Classes (JSS–SS)',
        25, 4),
      lesson('ibo-m6-l5',
        'Teaching Vowel Harmony & Onwu Orthography to Beginners',
        25, 5),
      lesson('ibo-m6-l6',
        'WAEC/NECO Oral & Written Exam Preparation — Mark Scheme & Strategies',
        30, 6),
    ]),
  ],

  /* ─────────────────────────────────────────────────── HAUSA ──────────────── */
  'hausa-language-teaching': [

    mod('hau-m1', 'Phonology, Orthography & the Hausa Writing Systems', 1, [
      lesson('hau-m1-l1',
        'Introduction to Hausa — Spread, Dialects (Kano, Sokoto, Zaria) & Standard Hausa',
        15, 1, true, 'https://www.youtube.com/watch?v=q5i_9UNnSjA'),
      lesson('hau-m1-l2',
        'Boko (Latin) Alphabet — Letters, Special Characters (ɓ, ɗ, ƙ, r̃) & NERDC Orthography',
        20, 2),
      lesson('hau-m1-l3',
        'Hausa Tone System — High Tone, Low Tone & Falling Tone (Circumflex)',
        25, 3),
      lesson('hau-m1-l4',
        'Vowel Length — Short vs Long Vowels & Their Role in Meaning',
        20, 4),
      lesson('hau-m1-l5',
        'Implosive & Ejective Consonants — ɓ, ɗ, ƙ, tʼ & Their Pronunciation',
        20, 5),
      lesson('hau-m1-l6',
        'Ajami Script — Introduction to Arabic-Based Hausa Writing',
        20, 6),
    ]),

    mod('hau-m2', 'Everyday Communication & Vocabulary Building', 2, [
      lesson('hau-m2-l1',
        'Greetings — Sannu, Barka, Ina kwana & Contextual Salutations',
        20, 1, true),
      lesson('hau-m2-l2',
        'Family, Kinship & Forms of Address (Baba, Mama, Yaya, Dan Uwa)',
        20, 2),
      lesson('hau-m2-l3',
        'Numbers, Counting (1–1000) & Hausa Ordinal System',
        25, 3),
      lesson('hau-m2-l4',
        'Market Hausa — Bargaining, Weights, Measures & Trade Vocabulary',
        20, 4),
      lesson('hau-m2-l5',
        'Days (Litinin to Lahadi), Months, Seasons & the Islamic Calendar',
        20, 5),
      lesson('hau-m2-l6',
        'Food, Clothing, Body Parts & Common Descriptive Vocabulary',
        20, 6),
    ]),

    mod('hau-m3', 'Hausa Grammar — NERDC SS1–SS3 Scope', 3, [
      lesson('hau-m3-l1',
        'Nouns — Gender (Masculine/Feminine), Pluralisation Patterns & Noun Classes',
        20, 1, true),
      lesson('hau-m3-l2',
        'Pronouns — Subject, Object, Possessive & Demonstrative Pronouns',
        20, 2),
      lesson('hau-m3-l3',
        'Verbs — Grade System (1–7), TAM Markers & Verbal Extensions',
        30, 3),
      lesson('hau-m3-l4',
        'Adjectives — Agreement with Noun Gender & Attributive vs Predicative Use',
        20, 4),
      lesson('hau-m3-l5',
        'Sentence Structure (SVO vs SOV Variation), Coordination & Subordination',
        25, 5),
      lesson('hau-m3-l6',
        'Questions (Shin, Wane/Wacce), Negation (ba…ba) & Imperative',
        20, 6),
      lesson('hau-m3-l7',
        'Prepositions (a, daga, zuwa, ga), Conjunctions & Connectors',
        20, 7),
    ]),

    mod('hau-m4', 'Reading & Writing Skills', 4, [
      lesson('hau-m4-l1',
        'Reading Hausa Texts — Tone Marks, Long Vowels & Fluency Development',
        20, 1, true),
      lesson('hau-m4-l2',
        'Comprehension — Passage Analysis, Inference & Vocabulary in Context',
        20, 2),
      lesson('hau-m4-l3',
        'Composition Writing — Labari (Narrative), Bayani (Expository) & Muhawara (Debate)',
        25, 3),
      lesson('hau-m4-l4',
        'Letter Writing — Wasika Takarda (Formal) & Informal Correspondence',
        25, 4),
      lesson('hau-m4-l5',
        'Summary Writing, Précis & Taƙaitawa Skills',
        20, 5),
      lesson('hau-m4-l6',
        'Dictation, Spelling Accuracy & Special Character Writing (ɓ, ɗ, ƙ)',
        20, 6),
    ]),

    mod('hau-m5', 'Literature & Oral Tradition (NERDC Set Works)', 5, [
      lesson('hau-m5-l1',
        'Karin Magana — Hausa Proverbs: Structure, Themes & Social Wisdom',
        20, 1, true),
      lesson('hau-m5-l2',
        'Tatsuniya — Folktales & Animal Fables: Motifs & Moral Lessons',
        25, 2),
      lesson('hau-m5-l3',
        'Waƙa — Classical Hausa Poetry: Metre (Aruz), Rhyme & Islamic Themes',
        25, 3),
      lesson('hau-m5-l4',
        'Zambo & Kirari — Satire, Praise Songs & Occupational Chants',
        25, 4),
      lesson('hau-m5-l5',
        'Modern Hausa Poetry & Prose — Themes of Identity, Migration & Change',
        25, 5),
      lesson('hau-m5-l6',
        'Prose Set Text — Reading & Analysing a Hausa Novel (NERDC Approved)',
        30, 6),
      lesson('hau-m5-l7',
        'Drama Set Text — Structure, Dialogue & Performance in Hausa Theatre',
        30, 7),
    ]),

    mod('hau-m6', 'Culture, Heritage & Pedagogy', 6, [
      lesson('hau-m6-l1',
        'Hausa-Fulani Emirate System — Sarki, Waziri & Traditional Governance',
        20, 1, true),
      lesson('hau-m6-l2',
        'Islam & Hausa Culture — Ramadan, Sallah (Eid), Naming Ceremonies & Marriage',
        20, 2),
      lesson('hau-m6-l3',
        'Hausa as a Lingua Franca — Spread Across West & Central Africa',
        20, 3),
      lesson('hau-m6-l4',
        'Hausa Crafts, Architecture & Material Culture (Kofar Mata, Indigo Dyeing)',
        20, 4),
      lesson('hau-m6-l5',
        'Lesson Planning for Hausa Language Classes (JSS–SS)',
        25, 5),
      lesson('hau-m6-l6',
        'WAEC/NECO Oral & Written Exam Preparation — Mark Scheme & Strategies',
        30, 6),
    ]),
  ],


  /* ═══════════════════════════════════════════════════════════════════════════
     AGRICULTURE SPECIALISATIONS — NERDC Agricultural Science Aligned
     Scope: NERDC Senior Secondary Agricultural Science SS1–SS3 Curriculum
            Federal Ministry of Agriculture & Rural Development guidelines
            NAFDAC / SON / NIRSAL / CBN ACGSF regulatory frameworks
  ═══════════════════════════════════════════════════════════════════════════ */

  /* ──────────────────────────────── POULTRY & FISH FARMING ─────────────── */
  'poultry-fish-farming': [

    mod('pff-m1', 'Foundations of Poultry Farming (NERDC SS2 Animal Production)', 1, [
      lesson('pff-m1-l1',
        'Why Poultry Farming? Opportunities in Nigeria\'s Protein Deficit Market',
        15, 1, true, 'https://www.youtube.com/watch?v=mfBFMCpPOkU'),
      lesson('pff-m1-l2',
        'Breeds & Strains — Layers (Isa Brown, Lohmann Brown) vs Broilers (Arbor Acres, Cobb 500)',
        20, 2),
      lesson('pff-m1-l3',
        'Poultry Housing Systems — Deep Litter, Battery Cage & Semi-Intensive',
        25, 3),
      lesson('pff-m1-l4',
        'Essential Equipment — Feeders, Drinkers, Heat Lamps, Incubators & Candlers',
        20, 4),
      lesson('pff-m1-l5',
        'Farm Biosecurity Level 1 — Access Control, Disinfection & Visitor Protocols',
        20, 5),
      lesson('pff-m1-l6',
        'Farm Records & Documentation — Production, Feed, Mortality & Financial Logs',
        20, 6),
    ]),

    mod('pff-m2', 'Layers & Egg Production Management', 2, [
      lesson('pff-m2-l1',
        'Layer Feeding Programme — Chick Starter, Pullet Grower & Layer Mash Formulations',
        25, 1, true),
      lesson('pff-m2-l2',
        'Light Management for Optimal Egg Production — Photoperiod & Lux Requirements',
        20, 2),
      lesson('pff-m2-l3',
        'Egg Collection, Grading, Storage & Quality Standards (SON NIS 99)',
        20, 3),
      lesson('pff-m2-l4',
        'Layer Vaccination Schedule — Newcastle Disease, Gumboro (IBD), Marek\'s & Fowl Pox',
        25, 4),
      lesson('pff-m2-l5',
        'Moulting Management & Planned Flock Replacement Strategy',
        20, 5),
      lesson('pff-m2-l6',
        'Project: 500-Bird Layer Farm — Production Budget & Break-Even Analysis',
        30, 6),
    ]),

    mod('pff-m3', 'Broiler & Meat Bird Production', 3, [
      lesson('pff-m3-l1',
        'Broiler Feeding Phases — Pre-Starter (Days 1–7), Starter, Grower & Finisher',
        25, 1, true),
      lesson('pff-m3-l2',
        'Brooding Management — Temperature Curves, Humidity & Ventilation',
        25, 2),
      lesson('pff-m3-l3',
        'Growth Performance Indicators — FCR, ADG, Livability & Uniformity',
        20, 3),
      lesson('pff-m3-l4',
        'Slaughter Weight Targets, Live Bird Markets & Processing for Retail',
        25, 4),
      lesson('pff-m3-l5',
        'Litter Management, Disinfection Protocols & All-In All-Out System',
        20, 5),
      lesson('pff-m3-l6',
        'Project: Full 6-Week Broiler Cycle — Production Plan & Profit Projection',
        30, 6),
    ]),

    mod('pff-m4', 'Fish Farming — Catfish & Tilapia (NERDC SS2 Aquaculture)', 4, [
      lesson('pff-m4-l1',
        'Introduction to Aquaculture in Nigeria — Species, Scale & Opportunities',
        15, 1, true),
      lesson('pff-m4-l2',
        'Pond Construction — Earthen Ponds, Concrete Tanks & Plastic Hapas (Tarpaulin Ponds)',
        25, 2),
      lesson('pff-m4-l3',
        'Water Quality Management — pH, Dissolved Oxygen, Ammonia, Temperature & Turbidity',
        25, 3),
      lesson('pff-m4-l4',
        'Catfish (Clarias & Heterobranchus) — Fingerling Sourcing, Stocking Density & Feeding',
        25, 4),
      lesson('pff-m4-l5',
        'Tilapia (GIFT Strain) — Mono-Sex Production, Stocking & Growth Management',
        25, 5),
      lesson('pff-m4-l6',
        'Project: Design, Stock & Manage a 500 m² Catfish Pond — Practical Simulation',
        30, 6),
    ]),

    mod('pff-m5', 'Disease Management & Biosecurity (NERDC SS2–SS3)', 5, [
      lesson('pff-m5-l1',
        'Common Poultry Diseases — Newcastle, Gumboro (IBD), Fowl Typhoid, Coccidiosis & Marek\'s',
        25, 1, true),
      lesson('pff-m5-l2',
        'Drug Administration Routes — Oral, Drinking Water, Injectable & Spray',
        20, 2),
      lesson('pff-m5-l3',
        'Common Fish Diseases — Bacterial Infections, Fungal & Parasitic (Ichthyophthirius)',
        20, 3),
      lesson('pff-m5-l4',
        'Biosecurity Level 2 — Quarantine, Fumigation & Post-Flock Disinfection',
        20, 4),
      lesson('pff-m5-l5',
        'Antibiotic Stewardship, Drug Withdrawal Periods & Residue Avoidance',
        20, 5),
      lesson('pff-m5-l6',
        'Emergency Protocols — Mass Mortality Investigation & Veterinary Liaison',
        20, 6),
    ]),

    mod('pff-m6', 'Business, Marketing & Value Chain', 6, [
      lesson('pff-m6-l1',
        'Costing a Poultry / Fish Farm — Capital & Recurrent Expenditure Breakdown',
        25, 1, true),
      lesson('pff-m6-l2',
        'Pricing Strategies — Live Weight, Dressed Weight, Eggs per Crate & Smoked Fish',
        20, 2),
      lesson('pff-m6-l3',
        'Finding Buyers — Open Markets, Hotels, Fast Food Chains, Supermarkets & Exporters',
        20, 3),
      lesson('pff-m6-l4',
        'Cold Chain Management — Refrigerated Transport & Storage for Poultry & Fish',
        20, 4),
      lesson('pff-m6-l5',
        'Value Addition — Smoked/Dried Fish, Frozen Chicken, Processed Eggs & Fish Feed',
        25, 5),
      lesson('pff-m6-l6',
        'Scaling Up — Cooperative Farming, Contract Schemes & Attracting Investment',
        25, 6),
    ]),
  ],

  /* ──────────────────────────────── AGRIBUSINESS MANAGEMENT ─────────────── */
  'agribusiness-management': [

    mod('agm-m1', 'Foundations of Agribusiness (NERDC Agric SS1–SS2)', 1, [
      lesson('agm-m1-l1',
        'What is Agribusiness? The Agriculture–Industry–Service Continuum',
        15, 1, true, 'https://www.youtube.com/watch?v=pJm5c8-sJXA'),
      lesson('agm-m1-l2',
        'The Nigerian Agribusiness Landscape — Sector Size, Gaps & Opportunities',
        20, 2),
      lesson('agm-m1-l3',
        'Types of Agribusiness Enterprises — Production, Processing, Inputs, Trade & Services',
        20, 3),
      lesson('agm-m1-l4',
        'Agribusiness Value Chains — Mapping Farm Gate to Consumer',
        25, 4),
      lesson('agm-m1-l5',
        'Key Players in Nigerian Agribusiness — Farmers, Processors, Traders, Government & NGOs',
        20, 5),
    ]),

    mod('agm-m2', 'Farm Business Planning (NERDC Agric SS2–SS3)', 2, [
      lesson('agm-m2-l1',
        'Writing a Farm Business Plan — The SMEDAN/BOI Approved Template',
        25, 1, true),
      lesson('agm-m2-l2',
        'Enterprise Selection — Matching Land, Capital, Climate & Skills',
        20, 2),
      lesson('agm-m2-l3',
        'Feasibility Analysis — Technical, Financial, Market & Management Dimensions',
        25, 3),
      lesson('agm-m2-l4',
        'Farm Layout & Infrastructure Planning — Roads, Water, Storage, Power',
        20, 4),
      lesson('agm-m2-l5',
        'Risk Management in Agriculture — Weather, Price, Pest & Credit Risks',
        20, 5),
    ]),

    mod('agm-m3', 'Agricultural Finance & Investment (NERDC SS3)', 3, [
      lesson('agm-m3-l1',
        'Farm Budgeting — Cash Flow, Income Statement & Balance Sheet',
        25, 1, true),
      lesson('agm-m3-l2',
        'CBN ACGSF, NIRSAL, Bank of Agriculture & BOI — Accessing Agricultural Loans',
        25, 2),
      lesson('agm-m3-l3',
        'State Grants, FADAMA III & Anchor Borrowers Programme (ABP)',
        20, 3),
      lesson('agm-m3-l4',
        'Cooperative Societies — Registration, Group Lending & Shared Infrastructure',
        20, 4),
      lesson('agm-m3-l5',
        'Farm Accounting & Records — Income, Expenses, Assets & Depreciation (NERDC SS3)',
        25, 5),
    ]),

    mod('agm-m4', 'Agricultural Marketing (NERDC SS3)', 4, [
      lesson('agm-m4-l1',
        'Understanding Agricultural Markets — Supply, Demand & Price Determination',
        20, 1, true),
      lesson('agm-m4-l2',
        'Market Channels in Nigeria — Producer, Wholesaler, Retailer & Consumer Linkages',
        20, 2),
      lesson('agm-m4-l3',
        'Agricultural Market Information Systems — Price Tracking & Decision-Making',
        20, 3),
      lesson('agm-m4-l4',
        'Contract Farming, Outgrower Schemes & Corporate Off-Take Agreements',
        25, 4),
      lesson('agm-m4-l5',
        'Export Markets — NEPC, AfCFTA Opportunities & NAFDAC Export Certification',
        25, 5),
    ]),

    mod('agm-m5', 'Agribusiness Operations & Technology (NERDC SS3)', 5, [
      lesson('agm-m5-l1',
        'Farm Mechanisation — Tractors, Two-Wheel Tillers, Planters & Combine Harvesters',
        20, 1, true),
      lesson('agm-m5-l2',
        'ICT in Agribusiness — Farmcrowdy, ThriveAgric, Hello Tractor & Digital Markets',
        20, 2),
      lesson('agm-m5-l3',
        'Agri-Inputs Supply Chain — Certified Seeds, Fertilisers, Pesticides & Sourcing',
        20, 3),
      lesson('agm-m5-l4',
        'Post-Harvest Technologies — Hermetic Bags, Silos, Cold Rooms & Solar Dryers',
        25, 4),
      lesson('agm-m5-l5',
        'Quality Management & Standards — SON, NAFDAC, GlobalGAP & Organic Certification',
        20, 5),
    ]),

    mod('agm-m6', 'Policy, Regulation & Agribusiness Scale-Up', 6, [
      lesson('agm-m6-l1',
        'Nigerian Agricultural Policy Framework — NAIP, Agricultural Promotion Policy (APP)',
        20, 1, true),
      lesson('agm-m6-l2',
        'Land Tenure & the Land Use Act — Accessing and Securing Farmland',
        20, 2),
      lesson('agm-m6-l3',
        'Agribusiness Registration — CAC, NAFDAC, SON, NEPC & State Agencies',
        20, 3),
      lesson('agm-m6-l4',
        'Attracting Investment — Angel Investors, Impact Funds & Agri-Tech Accelerators',
        25, 4),
      lesson('agm-m6-l5',
        'Building an Agribusiness Group — Cooperatives, Joint Ventures & Franchise Models',
        25, 5),
    ]),
  ],

  /* ──────────────────────────────── FOOD PROCESSING & VALUE ADDITION ──── */
  'food-processing-value-addition': [

    mod('fpv-m1', 'Introduction to Food Processing & Value Addition (NERDC Agric / Home Econ SS2)', 1, [
      lesson('fpv-m1-l1',
        'What is Value Addition? Transforming Farm Produce into High-Value Products',
        15, 1, true, 'https://www.youtube.com/watch?v=EUXnJraKM3k'),
      lesson('fpv-m1-l2',
        'Overview of Nigeria\'s Food Processing Industry — Size, Gaps & Opportunities',
        20, 2),
      lesson('fpv-m1-l3',
        'Food Processing & the War on Post-Harvest Losses — Up to 40% of Nigeria\'s Food',
        20, 3),
      lesson('fpv-m1-l4',
        'Career Pathways — Processor, Quality Inspector, Packager, Exporter & Consultant',
        15, 4),
      lesson('fpv-m1-l5',
        'Equipment & Facilities for Small-Scale Processing — Low-Capital Options',
        20, 5),
    ]),

    mod('fpv-m2', 'Post-Harvest Management & Storage (NERDC Agric SS3)', 2, [
      lesson('fpv-m2-l1',
        'Causes & Extent of Post-Harvest Losses in Nigeria — Grains, Roots, Fruits & Vegetables',
        20, 1, true),
      lesson('fpv-m2-l2',
        'Harvesting Techniques — Timing, Tools & Minimising Damage at Harvest',
        20, 2),
      lesson('fpv-m2-l3',
        'Primary Processing — Cleaning, Sorting, Grading & Sun Drying',
        20, 3),
      lesson('fpv-m2-l4',
        'Storage Methods — Ambient (Hermetic Bags, Silos), Refrigerated & Modified Atmosphere',
        25, 4),
      lesson('fpv-m2-l5',
        'Cold Chain Management — Temperature Monitoring for Perishable Products',
        20, 5),
    ]),

    mod('fpv-m3', 'Processing Technologies & Methods (NERDC SS2–SS3)', 3, [
      lesson('fpv-m3-l1',
        'Grain Processing — Maize Milling, Rice Parboiling, Gari & Fufu (Cassava) Production',
        25, 1, true),
      lesson('fpv-m3-l2',
        'Fruit & Vegetable Processing — Solar Drying, Juicing, Tomato Paste & Fermentation',
        25, 2),
      lesson('fpv-m3-l3',
        'Protein Processing — Smoking & Drying Fish, Sausages, Kilishi & Suya Products',
        25, 3),
      lesson('fpv-m3-l4',
        'Dairy Processing — Yoghurt, Wara Cheese, Nunu & Pasteurised Liquid Milk',
        20, 4),
      lesson('fpv-m3-l5',
        'Oils & Fats — Palm Oil Extraction, Groundnut Oil (Pressing) & Shea Butter Processing',
        25, 5),
    ]),

    mod('fpv-m4', 'Food Safety, Hygiene & NAFDAC Standards', 4, [
      lesson('fpv-m4-l1',
        'Good Manufacturing Practices (GMP) for Small Food Businesses — NAFDAC Guidelines',
        20, 1, true),
      lesson('fpv-m4-l2',
        'HACCP Simplified — Identifying Hazards, Critical Control Points & Corrective Actions',
        25, 2),
      lesson('fpv-m4-l3',
        'NAFDAC Registration Process — Step-by-Step Guide for Small Processors',
        25, 3),
      lesson('fpv-m4-l4',
        'SON Food Standards — NIS Labelling Requirements & Nutritional Information',
        20, 4),
      lesson('fpv-m4-l5',
        'Food Microbiology Basics — Pathogens, Spoilage Organisms & Preservation Principles',
        20, 5),
    ]),

    mod('fpv-m5', 'Packaging, Branding & Marketing', 5, [
      lesson('fpv-m5-l1',
        'Packaging Materials — Plastics, Glass, Aluminium Foil, Paper & Eco-Friendly Options',
        20, 1, true),
      lesson('fpv-m5-l2',
        'Designing Labels That Meet NAFDAC Requirements — Mandatory Information',
        20, 2),
      lesson('fpv-m5-l3',
        'Branding Your Food Product — Name, Logo, Colour, Story & Positioning',
        20, 3),
      lesson('fpv-m5-l4',
        'Pricing for Retail & Wholesale — Costing, Margins & Competitive Pricing',
        20, 4),
      lesson('fpv-m5-l5',
        'Distribution Channels — Open Markets, Supermarkets, Online (Jumia Food) & Hotels',
        20, 5),
    ]),

    mod('fpv-m6', 'Building Your Food Processing Business', 6, [
      lesson('fpv-m6-l1',
        'Writing a Food Business Plan — SMEDAN / MSME Template',
        20, 1, true),
      lesson('fpv-m6-l2',
        'Equipment Financing — Hire Purchase, Leasing & MSME Loan Programmes',
        20, 2),
      lesson('fpv-m6-l3',
        'Quality Management & Continuous Improvement — SOP, Audit & Certification',
        20, 3),
      lesson('fpv-m6-l4',
        'Industry Associations — NAMDAS, FDAN, NIFST & Cooperative Benefits',
        15, 4),
      lesson('fpv-m6-l5',
        'Exporting Processed Nigerian Foods — NEPC, SON Certification & Phytosanitary Standards',
        25, 5),
    ]),
  ],

  /* ──────────────────────────────── HORTICULTURE — URBAN MARKETS ─────── */
  'horticulture-urban-markets': [

    mod('hum-m1', 'Introduction to Horticulture & Urban Farming (NERDC Agric SS1)', 1, [
      lesson('hum-m1-l1',
        'What is Horticulture? Olericulture, Pomology & Floriculture — NERDC Definition & Scope',
        15, 1, true, 'https://www.youtube.com/watch?v=9Yz9OAkOhbI'),
      lesson('hum-m1-l2',
        'Urban & Peri-Urban Agriculture — The Growing Demand in Nigerian Cities',
        20, 2),
      lesson('hum-m1-l3',
        'Urban Farming Systems — Raised Beds, Container Gardening, Rooftop & Greenhouse Farming',
        20, 3),
      lesson('hum-m1-l4',
        'Site Selection — Sunlight, Water Access, Soil Quality & Proximity to Markets',
        20, 4),
      lesson('hum-m1-l5',
        'Market Study — Identifying High-Demand Vegetables in Your City (Lagos, Abuja, PHC)',
        20, 5),
    ]),

    mod('hum-m2', 'Soil Preparation & Fertility Management (NERDC Agric SS1 — Soil Science)', 2, [
      lesson('hum-m2-l1',
        'Soil Types for Vegetables — Sandy Loam, Clay, Silt & the Ideal pH Range (6.0–7.0)',
        20, 1, true),
      lesson('hum-m2-l2',
        'Soil Testing — DIY pH Test, Nutrient Deficiency Signs & Lab Analysis',
        20, 2),
      lesson('hum-m2-l3',
        'Composting & Organic Matter — Making Compost from Kitchen & Farm Waste',
        25, 3),
      lesson('hum-m2-l4',
        'Fertiliser Application — NPK Rates, Timing & Methods for Common Vegetables',
        25, 4),
      lesson('hum-m2-l5',
        'Irrigation for Vegetable Gardens — Drip, Sprinkler, Furrow & Watering Cans',
        20, 5),
    ]),

    mod('hum-m3', 'Vegetable Crop Production (NERDC Agric SS1–SS2)', 3, [
      lesson('hum-m3-l1',
        'Leafy Vegetables — Ugwu (Fluted Pumpkin), Waterleaf, Bitter Leaf, Spinach & Cabbage',
        25, 1, true),
      lesson('hum-m3-l2',
        'Fruiting Vegetables — Tomatoes, Pepper (Tatashe & Scotch Bonnet), Garden Egg & Okra',
        25, 2),
      lesson('hum-m3-l3',
        'Root & Bulb Crops — Carrot, Onion, Garlic, Radish & Sweet Potato',
        25, 3),
      lesson('hum-m3-l4',
        'Nursery Management — Seed Germination, Nursery Beds, Pricking Out & Transplanting',
        20, 4),
      lesson('hum-m3-l5',
        'Crop Spacing, Staking, Training & Trellising for Maximum Yield',
        20, 5),
      lesson('hum-m3-l6',
        'Harvesting Indicators & Techniques for Different Vegetable Crops',
        20, 6),
    ]),

    mod('hum-m4', 'Pest & Disease Management (NERDC Agric SS2)', 4, [
      lesson('hum-m4-l1',
        'Major Vegetable Pests — Aphids, Whitefly, Leaf Miners, Thrips & Caterpillars',
        20, 1, true),
      lesson('hum-m4-l2',
        'Common Vegetable Diseases — Downy Mildew, Bacterial Wilt, Anthracnose & Late Blight',
        20, 2),
      lesson('hum-m4-l3',
        'Integrated Pest Management (IPM) — Cultural, Biological & Chemical Control',
        25, 3),
      lesson('hum-m4-l4',
        'Pesticide Safety — Label Reading, PPE, Dosage Calculation & Pre-Harvest Interval (PHI)',
        20, 4),
      lesson('hum-m4-l5',
        'Record-Keeping for Pest & Disease Management — Spray Log & Scouting Diary',
        15, 5),
    ]),

    mod('hum-m5', 'Harvesting, Post-Harvest & Market Access (NERDC SS3)', 5, [
      lesson('hum-m5-l1',
        'Harvesting at Commercial Maturity — Quality Standards for Urban Buyers',
        20, 1, true),
      lesson('hum-m5-l2',
        'Grading & Packaging for Different Market Segments — Open Market vs Supermarket',
        20, 2),
      lesson('hum-m5-l3',
        'Post-Harvest Handling — Field Heat Removal, Washing, Sorting & Crating',
        20, 3),
      lesson('hum-m5-l4',
        'Urban Market Channels — Open Markets, Hotels, Restaurants, Supermarkets & Online',
        20, 4),
      lesson('hum-m5-l5',
        'Pricing Strategies — Seasonal Pricing, Contract Supply & Collective Marketing',
        20, 5),
    ]),

    mod('hum-m6', 'Urban Farming Systems & Business', 6, [
      lesson('hum-m6-l1',
        'Container & Raised-Bed Vegetable Production at Commercial Scale',
        20, 1, true),
      lesson('hum-m6-l2',
        'Introduction to Hydroponic & Soilless Farming — Economics & Getting Started',
        25, 2),
      lesson('hum-m6-l3',
        'Building a Vegetable Farming Enterprise — Business Plan & Financial Projections',
        25, 3),
      lesson('hum-m6-l4',
        'Cooperative Vegetable Production & Aggregation for Large Urban Buyers',
        20, 4),
    ]),
  ],

  /* ──────────────────────────────── IRRIGATION FARMING — DRY SEASON ───── */
  'irrigation-farming-dry-season': [

    mod('ifd-m1', 'Introduction to Irrigation Farming (NERDC Agric SS1 Water Management)', 1, [
      lesson('ifd-m1-l1',
        'What is Irrigation? Importance of Dry Season Farming for Food Security in Nigeria',
        15, 1, true, 'https://www.youtube.com/watch?v=Mi6OJ4zbLX4'),
      lesson('ifd-m1-l2',
        'Nigeria\'s River Systems & Groundwater Resources — Niger, Benue, Hadejia, Lake Chad Basin',
        20, 2),
      lesson('ifd-m1-l3',
        'Types of Irrigation — Surface (Flood/Furrow), Sprinkler & Drip — Advantages & Limitations',
        25, 3),
      lesson('ifd-m1-l4',
        'Economic Importance of Dry Season Farming — Income, Food Security & Employment',
        15, 4),
      lesson('ifd-m1-l5',
        'Case Studies — Successful Irrigated Farming Communities (Kano River, Fadama, Benue Valley)',
        20, 5),
    ]),

    mod('ifd-m2', 'Water Sources & Irrigation Infrastructure (NERDC Agric SS2)', 2, [
      lesson('ifd-m2-l1',
        'Surface Water Sources — Rivers, Streams, Reservoirs, Fadama Wetlands & Dugout Ponds',
        20, 1, true),
      lesson('ifd-m2-l2',
        'Groundwater — Boreholes, Shallow Tube Wells, Hand-Dug Wells & Water Quality Testing',
        20, 2),
      lesson('ifd-m2-l3',
        'Water Lifting Devices — Petrol/Diesel Pumps, Solar Pumps, Treadle Pumps & Rope Pumps',
        25, 3),
      lesson('ifd-m2-l4',
        'Irrigation System Design — Layout Planning, Pipe Sizing, Channel Design & Head Loss',
        25, 4),
      lesson('ifd-m2-l5',
        'Operation & Maintenance of Irrigation Infrastructure — Schedules & Cost Sharing',
        20, 5),
    ]),

    mod('ifd-m3', 'Dry Season Crop Selection & Production Calendar (NERDC Agric SS2)', 3, [
      lesson('ifd-m3-l1',
        'Crop Selection Criteria for Dry Season Production — Water Use Efficiency & Market Value',
        20, 1, true),
      lesson('ifd-m3-l2',
        'Vegetables for Dry Season — Tomatoes, Pepper, Onion (Gawuna), Garlic & Cabbage',
        25, 2),
      lesson('ifd-m3-l3',
        'Cereals & Legumes — Dry Season Maize, Cowpea (Beans) & Sesame (Beniseed)',
        20, 3),
      lesson('ifd-m3-l4',
        'Oil Crops — Dry Season Groundnut Production & Sunflower',
        20, 4),
      lesson('ifd-m3-l5',
        'Irrigation Planting Calendars — Timing Crop Cycles with Water Availability',
        20, 5),
      lesson('ifd-m3-l6',
        'Crop Rotation & Intercropping Strategies for Irrigated Systems',
        20, 6),
    ]),

    mod('ifd-m4', 'Irrigation Scheduling & Water Management (NERDC Agric SS3)', 4, [
      lesson('ifd-m4-l1',
        'Evapotranspiration (ET) — Understanding Crop Water Requirements by Growth Stage',
        25, 1, true),
      lesson('ifd-m4-l2',
        'Calculating Irrigation Intervals, Water Volumes & Application Rates',
        25, 2),
      lesson('ifd-m4-l3',
        'Drip Irrigation Scheduling — Emitter Selection, Flow Rates & Irrigation Set Duration',
        25, 3),
      lesson('ifd-m4-l4',
        'Sprinkler Irrigation Management — Head Spacing, Operating Pressure & Uniformity',
        20, 4),
      lesson('ifd-m4-l5',
        'Water Harvesting & Conservation Techniques — Bunds, Zai Pits & Mulching',
        20, 5),
    ]),

    mod('ifd-m5', 'Soil Health Under Irrigation (NERDC Agric SS2–SS3)', 5, [
      lesson('ifd-m5-l1',
        'Soil Salinity — Causes, EC Measurement, Threshold Levels & Leaching Management',
        20, 1, true),
      lesson('ifd-m5-l2',
        'Waterlogging & Drainage — Surface Drainage & Subsurface Pipe Drain Design',
        25, 2),
      lesson('ifd-m5-l3',
        'Fertiliser Management Under Irrigation — Split Application & Fertigation Basics',
        25, 3),
      lesson('ifd-m5-l4',
        'Maintaining Soil Organic Matter Under Irrigated Conditions — Cover Crops & Mulch',
        20, 4),
      lesson('ifd-m5-l5',
        'Soil & Water Conservation Practices — Contour Ridges, Windbreaks & Minimum Tillage',
        20, 5),
    ]),

    mod('ifd-m6', 'Business Planning for Irrigation Farming', 6, [
      lesson('ifd-m6-l1',
        'Costing an Irrigation Scheme — Capital (Pump, Pipes, Land), Water & Operating Costs',
        25, 1, true),
      lesson('ifd-m6-l2',
        'Government & State Irrigation Schemes — LCRI, River Basin Authorities & FADAMA Access',
        20, 2),
      lesson('ifd-m6-l3',
        'World Bank / IFAD Supported Irrigation Programmes in Nigeria — How to Join',
        20, 3),
      lesson('ifd-m6-l4',
        'Building a Year-Round Farming Enterprise — Business Plan, Finances & Market Strategy',
        25, 4),
    ]),
  ],

  /* ─────────────────────────────────────────────────── */
  'keyboard-piano-music-business': [
    mod('kpb-m1', 'Keyboard & Piano Foundations', 1, [
      lesson('kpb-m1-l1',
        'The Piano/Keyboard Layout, Posture & Hand Position',
        15, 1, true, 'https://www.youtube.com/watch?v=QBH6IpRkVDs'),
      lesson('kpb-m1-l2',
        'Reading Music — Notes, the Staff & Rhythm Basics',
        20, 2),
      lesson('kpb-m1-l3',
        'Choosing & Setting Up Your Keyboard — Sizes, Weighted Keys & the Sustain Pedal',
        15, 3),
      lesson('kpb-m1-l4',
        'Finger Numbering & Basic Hand Coordination Exercises',
        20, 4),
      lesson('kpb-m1-l5',
        'Your First Scale — C Major, Both Hands',
        20, 5),
      lesson('kpb-m1-l6',
        'Simple Melodies — Playing Your First Song',
        20, 6),
    ]),

    mod('kpb-m2', 'Chords & Harmony for Gospel, Afrobeats & Highlife', 2, [
      lesson('kpb-m2-l1',
        'Major & Minor Triads — Building Your First Chords',
        20, 1, true),
      lesson('kpb-m2-l2',
        'The I–IV–V Progression — The Foundation of Popular Music',
        20, 2),
      lesson('kpb-m2-l3',
        '7th Chords & the Gospel Sound',
        25, 3),
      lesson('kpb-m2-l4',
        'Playing By Ear — Finding Chords From a Song You Hear',
        25, 4),
      lesson('kpb-m2-l5',
        'Nigerian Gospel & Highlife Chord Patterns',
        25, 5),
      lesson('kpb-m2-l6',
        'Accompanying a Singer or Choir',
        25, 6),
    ]),

    mod('kpb-m3', 'Technique, Rhythm & Groove', 3, [
      lesson('kpb-m3-l1',
        'Left-Hand Bass Patterns & Walking Bass',
        20, 1, true),
      lesson('kpb-m3-l2',
        'Afrobeats & Amapiano Keyboard Grooves',
        25, 2),
      lesson('kpb-m3-l3',
        'Improvisation Basics — Riffs, Fills & Runs',
        25, 3),
      lesson('kpb-m3-l4',
        'Playing With a Metronome & Building Speed',
        20, 4),
      lesson('kpb-m3-l5',
        'Dynamics & Expression — Playing With Feeling',
        20, 5),
      lesson('kpb-m3-l6',
        'Practice Routines That Actually Work',
        15, 6),
    ]),

    mod('kpb-m4', 'Live Performance & Playing With a Band', 4, [
      lesson('kpb-m4-l1',
        'Reading a Chord Chart / Lead Sheet on the Spot',
        20, 1, true),
      lesson('kpb-m4-l2',
        'Playing With a Drummer, Bassist & Guitarist',
        25, 2),
      lesson('kpb-m4-l3',
        'Stage Setup — Keyboard Stand, Sustain Pedal, Power & Cables',
        15, 3),
      lesson('kpb-m4-l4',
        'In-Ear Monitors, Sound Check & Stage Etiquette',
        20, 4),
      lesson('kpb-m4-l5',
        'Handling Mistakes & Performance Nerves',
        15, 5),
      lesson('kpb-m4-l6',
        'Project: Record a 3-Song Live Performance Set',
        30, 6),
    ]),

    mod('kpb-m5', 'Recording & Home Studio Basics', 5, [
      lesson('kpb-m5-l1',
        'Setting Up a Simple Home Recording Setup',
        20, 1, true),
      lesson('kpb-m5-l2',
        'Introduction to a DAW — GarageBand / FL Studio Mobile',
        25, 2),
      lesson('kpb-m5-l3',
        'Recording Keyboard Parts & Basic Editing',
        25, 3),
      lesson('kpb-m5-l4',
        'Layering Sounds — Pads, Strings & Bass in Your Arrangement',
        20, 4),
      lesson('kpb-m5-l5',
        'Creating a Demo Reel / Portfolio Video',
        20, 5),
      lesson('kpb-m5-l6',
        'Project: Produce a 2-Minute Instrumental Demo',
        30, 6),
    ]),

    mod('kpb-m6', 'Music Business & Entrepreneurship', 6, [
      lesson('kpb-m6-l1',
        'Nigeria\'s Music Economy — Where Keyboardists Actually Get Paid',
        20, 1, true),
      lesson('kpb-m6-l2',
        'Pricing Your Services — Church Gigs, Weddings, Studio Sessions & Corporate Events',
        25, 2),
      lesson('kpb-m6-l3',
        'Getting Your First Paying Gigs — Networking, Referrals & Church Music Departments',
        20, 3),
      lesson('kpb-m6-l4',
        'Teaching Keyboard Lessons for Recurring Income',
        20, 4),
      lesson('kpb-m6-l5',
        'Selling Beats, Jingles & Session Work Online',
        20, 5),
      lesson('kpb-m6-l6',
        'Branding Yourself as a Musician & Building a Client Pipeline',
        30, 6),
    ]),
  ],

}

/** Flat lookup: lessonId → { module, lesson, courseSlug } */
export function findLesson(courseSlug: string, lessonId: string) {
  const modules = COURSE_CURRICULUM[courseSlug] ?? []
  for (const mod of modules) {
    for (const lesson of mod.lessons) {
      if (lesson.id === lessonId) {
        return { module: mod, lesson }
      }
    }
  }
  return null
}

/** All lessons in a course in order */
export function allLessons(courseSlug: string): CurriculumLesson[] {
  return (COURSE_CURRICULUM[courseSlug] ?? []).flatMap(m => m.lessons)
}
