import type { Course } from '@/types'

export const STATIC_COURSES: Course[] = [
  {
    id: 'static-1', slug: 'digital-marketing-mastery',
    title: 'Digital Marketing Mastery',
    description: 'Master social media ads, SEO, email marketing, and content strategy to grow any business online.',
    category: 'digital_marketing', target_role: 'youth', language: 'en',
    available_langs: ['en', 'yo', 'pcm'], duration_weeks: 4, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 15000,
    total_lessons: 24, total_enrolled: 2400, avg_rating: 4.8, tags: ['marketing', 'social media'],
  },
  {
    id: 'static-2', slug: 'social-media-management',
    title: 'Social Media Management',
    description: 'Build and manage brand presence on Instagram, TikTok, Facebook and Twitter for clients.',
    category: 'digital_marketing', target_role: 'youth', language: 'en',
    available_langs: ['en', 'pcm'], duration_weeks: 3, is_free: true,
    is_published: true, is_offline_ready: true, price_ngn: 0,
    total_lessons: 18, total_enrolled: 3100, avg_rating: 4.7, tags: ['social media', 'content'],
  },
  {
    id: 'static-3', slug: 'coding-basics',
    title: 'Coding Basics for Beginners',
    description: 'Learn HTML, CSS and JavaScript from scratch. Build real websites and earn as a freelance developer.',
    category: 'coding', target_role: 'youth', language: 'en',
    available_langs: ['en', 'yo', 'ig'], duration_weeks: 6, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 20000,
    total_lessons: 36, total_enrolled: 1800, avg_rating: 4.9, tags: ['coding', 'web', 'javascript'],
  },
  {
    id: 'static-4', slug: 'python-data-skills',
    title: 'Python & Data Skills',
    description: 'Learn Python programming and basic data analysis. In-demand skills for tech and finance sectors.',
    category: 'coding', target_role: 'youth', language: 'en',
    available_langs: ['en'], duration_weeks: 8, is_free: false,
    is_published: true, is_offline_ready: false, price_ngn: 25000,
    total_lessons: 40, total_enrolled: 950, avg_rating: 4.8, tags: ['python', 'data', 'tech'],
  },
  {
    id: 'static-5', slug: 'fashion-design-fundamentals',
    title: 'Fashion Design & Tailoring',
    description: 'From pattern drafting to garment construction. Launch your own fashion brand in Nigeria.',
    category: 'fashion_design', target_role: 'youth', language: 'en',
    available_langs: ['en', 'ig', 'yo'], duration_weeks: 6, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 12000,
    total_lessons: 30, total_enrolled: 2200, avg_rating: 4.9, tags: ['fashion', 'sewing', 'business'],
  },
  {
    id: 'static-6', slug: 'solar-installation-tech',
    title: 'Solar Panel Installation',
    description: 'Install, wire and maintain solar power systems. High-demand trade across Nigeria.',
    category: 'solar_tech', target_role: 'youth', language: 'en',
    available_langs: ['en', 'ha', 'yo'], duration_weeks: 5, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 18000,
    total_lessons: 28, total_enrolled: 1600, avg_rating: 4.7, tags: ['solar', 'electrical', 'trade'],
  },
  {
    id: 'static-7', slug: 'agribusiness-fundamentals',
    title: 'Agribusiness Fundamentals',
    description: 'Turn farming into a profitable business. Covers crop production, poultry, fish farming and marketing.',
    category: 'agribusiness', target_role: 'youth', language: 'en',
    available_langs: ['en', 'ha', 'ig', 'yo'], duration_weeks: 4, is_free: true,
    is_published: true, is_offline_ready: true, price_ngn: 0,
    total_lessons: 20, total_enrolled: 4100, avg_rating: 4.8, tags: ['farming', 'agriculture', 'business'],
  },
  {
    id: 'static-8', slug: 'financial-literacy-nigeria',
    title: 'Financial Literacy & Money Management',
    description: 'Budgeting, saving, investing and avoiding debt. Essential money skills for every Nigerian.',
    category: 'financial_literacy', target_role: 'youth', language: 'en',
    available_langs: ['en', 'pcm', 'yo'], duration_weeks: 3, is_free: true,
    is_published: true, is_offline_ready: true, price_ngn: 0,
    total_lessons: 15, total_enrolled: 5200, avg_rating: 4.9, tags: ['finance', 'savings', 'investing'],
  },
  {
    id: 'static-9', slug: 'entrepreneurship-nigeria',
    title: 'Entrepreneurship & Business Launch',
    description: 'Validate your idea, register your business, get funding and scale in the Nigerian market.',
    category: 'entrepreneurship', target_role: 'youth', language: 'en',
    available_langs: ['en', 'pcm'], duration_weeks: 4, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 10000,
    total_lessons: 22, total_enrolled: 3300, avg_rating: 4.7, tags: ['business', 'startup', 'SME'],
  },
  {
    id: 'static-10', slug: 'graphic-design-canva',
    title: 'Graphic Design with Canva & Photoshop',
    description: 'Create logos, flyers, social media posts and brand kits. Earn from freelance design jobs.',
    category: 'digital_marketing', target_role: 'youth', language: 'en',
    available_langs: ['en', 'yo'], duration_weeks: 4, is_free: false,
    is_published: true, is_offline_ready: false, price_ngn: 12000,
    total_lessons: 26, total_enrolled: 1700, avg_rating: 4.8, tags: ['design', 'canva', 'creative'],
  },
  {
    id: 'static-11', slug: 'catering-food-business',
    title: 'Catering & Food Business',
    description: 'Start a profitable catering or food delivery business. Learn recipes, pricing and marketing.',
    category: 'entrepreneurship', target_role: 'youth', language: 'en',
    available_langs: ['en', 'ig', 'yo'], duration_weeks: 3, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 8000,
    total_lessons: 16, total_enrolled: 2800, avg_rating: 4.6, tags: ['food', 'catering', 'business'],
  },
  {
    id: 'static-12', slug: 'logistics-supply-chain',
    title: 'Logistics & Supply Chain Basics',
    description: 'Understand how goods move from producer to consumer. Work with top logistics companies in Nigeria.',
    category: 'entrepreneurship', target_role: 'youth', language: 'en',
    available_langs: ['en'], duration_weeks: 3, is_free: false,
    is_published: true, is_offline_ready: false, price_ngn: 10000,
    total_lessons: 18, total_enrolled: 820, avg_rating: 4.5, tags: ['logistics', 'supply chain', 'operations'],
  },

  // ── Nigerian Languages ────────────────────────────────────────────────────
  {
    id: 'static-13', slug: 'yoruba-language-teaching',
    title: 'Yoruba Language: Speak, Read & Teach',
    description: 'Master Yoruba tones, grammar, proverbs and literature. Ideal for teachers, heritage speakers and anyone who wants to connect with Yoruba culture.',
    category: 'languages', target_role: 'youth', language: 'yo',
    available_langs: ['yo', 'en'], duration_weeks: 5, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 10000,
    total_lessons: 37, total_enrolled: 1850, avg_rating: 4.9, tags: ['yoruba', 'language', 'culture', 'teaching'],
  },
  {
    id: 'static-14', slug: 'igbo-language-teaching',
    title: 'Igbo Language: Speak, Read & Teach',
    description: 'Learn Igbo alphabet, tones, grammar, proverbs and oral traditions. Perfect for teachers, the diaspora and learners reconnecting with Igbo identity.',
    category: 'languages', target_role: 'youth', language: 'ig',
    available_langs: ['ig', 'en'], duration_weeks: 5, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 10000,
    total_lessons: 37, total_enrolled: 1620, avg_rating: 4.8, tags: ['igbo', 'language', 'culture', 'teaching'],
  },
  {
    id: 'static-15', slug: 'hausa-language-teaching',
    title: 'Hausa Language: Speak, Read & Teach',
    description: 'Learn Hausa pronunciation, grammar, literature and proverbs. A vital language of trade and education across northern Nigeria and West Africa.',
    category: 'languages', target_role: 'youth', language: 'ha',
    available_langs: ['ha', 'en'], duration_weeks: 5, is_free: false,
    is_published: true, is_offline_ready: true, price_ngn: 10000,
    total_lessons: 37, total_enrolled: 1430, avg_rating: 4.8, tags: ['hausa', 'language', 'culture', 'teaching'],
  },
]
